name: My Test Workflow
'on': 
  push:
   branches:
     - main
     - 'feature/*'
jobs:
  my-test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Run Test Workflow
        run: 'echo "Hello, World!"'
