name: Process OpenAPI
'on':
  push:
    branches: 
     - main
     - 'feature/*'      # Matches feature/test, but NOT feature/test/ui
jobs:
  process-openapi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - run: npm install
      - run: npm test
      - run: npm run build
      - name: Generate processed OpenAPI
        run: npm run process -- openapi.yml openapi.processed.yml
      - uses: actions/upload-artifact@v4
        with:
          name: processed-openapi
          path: openapi.processed.yml
