name: My Test Workflow
'on': 
  push:
   branches:
     - feature-test
     #- 'feature/*'
jobs:
  my-test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Run Test Workflow
        run: 'echo "First test workflow executed successfully!"'
